### ISSUE TITLE
Preview indivuduele titel werk niet

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#1]
Selecteer 1 titel, bv "1. Het aambeeld". Klik op Preview. 

Resultaat: Foutmelding 

 cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
500 Internal Server Error - RequestException 
![bug2](https://cloud.githubusercontent.com/assets/6546244/12423439/c7632aca-becb-11e5-9014-b1689f2fd2b5.JPG)
![bug1](https://cloud.githubusercontent.com/assets/6546244/12423438/c760e49a-becb-11e5-9243-350181912fc6.JPG)

 CRITICAL - Uncaught PHP Exception GuzzleHttp\Exception\RequestException: "cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)" at C:\temp\xampp\htdocs\verzetskranten\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php line 187

**Comment by ookgezellig** [comment]
Werkt na laatste pull beter maar nog niet 100%

Als ik Winkel nr 1 (Het Aambeeld: het katholiek weekorgaan (verzetsblad, Leeuwarden) preview, dan gaat het goed (zie screenshot)
![bug12](https://cloud.githubusercontent.com/assets/6546244/12451526/481406b2-bf8a-11e5-974b-b141b2cc662d.JPG)

als ik Winkel nr 1004 preview gaat het fout, (screenshots)
![bug14](https://cloud.githubusercontent.com/assets/6546244/12451571/82eda37e-bf8a-11e5-92d0-fe110fa67588.JPG)
![bug13](https://cloud.githubusercontent.com/assets/6546244/12451572/82eda144-bf8a-11e5-8ab7-d5b7a6bfea64.JPG)

**Comment by rokkie** [comment]
Dat veld had geen default, net gefixed.

**Comment by ookgezellig** [comment]
Getest, daat nu goed!

Heb ook nog de previews van een roedel andere titels getest, gaat ook allemaal goed. Deze issue sluit ik dus
