### ISSUE TITLE
Feedback bij correct/incorrect wachtwoord ontbreekt

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#10]
Als ik mijn Wikipedia username en wachtwoord invul en op Login klik, verwacht ik feedback te krijgen of de login succesvol is geweest, of niet is. Nu gebeurt er niets 

![bug9](https://cloud.githubusercontent.com/assets/6546244/12446293/7b6eaede-bf69-11e5-9d3f-b41e1ea65c38.JPG)

**Comment by rokkie** [comment]
Klopt, dit moet nog gemaakt worden. Als je successvol bent ingelogd zou je wel een melding moeten zien zoals hieronder:
![screenshot from 2016-01-20 12 07 21](https://cloud.githubusercontent.com/assets/1914675/12447179/ba801360-bf6e-11e5-91b0-4e6b4b804878.png)

**Comment by ookgezellig** [comment]
RE: "Als je successvol bent ingelogd zou je wel een melding moeten zien zoals hieronder:"

Ik kan dit niet reproduceren: ik heb het geprobeerd in Firefox en Chrome (en de cache geleegd door op Kaboom te klikken, en mijn Wikipedia-ww geverifieerd), maar zonder succes.

**Comment by rokkie** [comment]
Ik zal sowieso even de feedback voor failure inbouwen, dan krijgen we meer teweten waarom dit mis gaat.

**Comment by ookgezellig** [comment]
Na de laatste pull werkt de login nu wel, zie screenshot

![bug11](https://cloud.githubusercontent.com/assets/6546244/12451230/70e650ba-bf88-11e5-8655-8c4be109be77.JPG)

(ik heb een export van Winkel nr 54 geprobeerd, dat lukt nog niet (maar da's een aparte issue)

**Comment by rokkie** [comment]
Krijg je die warning nu bij het exporteren of bij het inloggen?

**Comment by ookgezellig** [comment]
Bij het exporteren, het inloggen gaat nu goed

**Comment by rokkie** [comment]
Ik heb nog 1 fix toegepast, je zou het nog eens kunnen proberen.

**Comment by ookgezellig** [comment]
Gestest: nu goede feedback bij onvolldig/incorrecte username en ww

Issue kan dus dicht
