### ISSUE TITLE
Delpher Link

### ISSUE THREAD

**Issue by rokkie** [ookgezellig/verzetskranten#11]
Er lijkt geeneen blad te zijn met een link naar delpher. Het lijkt erop dat de query die de bladen ophaalt geen resultaat oplevert.

**Comment by ookgezellig** [comment]
Je moet de andere PPN gebruiken. 

Bv bij Winkel nr 4 : 
http://www.delpher.nl/nl/kranten/results/index?coll=dddtitel&cql[]=ppn%3D851959695
(dus niet http://www.delpher.nl/nl/kranten/results/index?coll=dddtitel&cql[]=ppn%3D376312769

**Comment by ookgezellig** [comment]
Getest, gaat nu goed. Ik sluit de issue
