### ISSUE TITLE
Export (individueel artikel) naar Wikipedia werkt niet

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#12]
Ik log in met mijn WP user (OlafJanssen) en password.(ik ontvang geen feedback of deze login succesvol is of niet, zie aparte issue hierover). Aannemende dat ik inderdaad succesvol ben ingelogd, selecteer ik een titel, bv. "Berichten van de GPD (Geallieerde Persdienst) (verzetsblad, Tilburg)" (Winkel 54).

Ik klik nu op "Export" en zou verwachten dat er een artikel op https://nl.wikipedia.org/wiki/Wikipedia:Wikiproject/Verzetskranten/Beginnetjes/Berichten van de GPD (Geallieerde Persdienst) (verzetsblad, Tilburg) zou verschijnen. Dat gebeurt niet. 

Als ik mijn lijst van bijdragen op WP check (zie screenshot), dan zie ik daar ook geen nieuwe edit verschijnen. 
![bug10](https://cloud.githubusercontent.com/assets/6546244/12446504/b2518b6e-bf6a-11e5-9c22-a9f2136ea518.JPG)
![bug9](https://cloud.githubusercontent.com/assets/6546244/12446509/ba194ea4-bf6a-11e5-8e91-c17254fdf8fd.JPG)

**Comment by ookgezellig** [comment]
Na ingelogd te hebben, selecteer ik Winkel nr 54 en klik op Export. Krijg dan een foutmelding "Requested token type 'edittoken' was not present in the response", zie ook 
![bug19](https://cloud.githubusercontent.com/assets/6546244/12511174/8475b20a-c10f-11e5-93b4-d485c6cf4077.JPG)
screenshot

**Comment by rokkie** [comment]
Ik heb net zelf even een test gedaan met exporteren. Dat ging met wisselend success.
Eerst mislukte het omdat ie om een captcha vroeg, daarna ging het ineens wel goed, maar is ie' meteen in de hoofdnaamruimte gegaan.

**Comment by ookgezellig** [comment]
OK. Besteed er nu maar verder geen aandacht aan, heeft geen acute prio, is voor later...

**Comment by rokkie** [comment]
Ok

**Comment by rokkie** [comment]
Ik heb hier nog aan gewerkt, ik heb het blad 'Margriet' successvol geexporteerd naar de 'Beginnetjes' namespace. Ik zie m alleen niet als een edit van mij, maar hij wordt wel bewerkt.
Je kunt nu ook vanuit de preview exporteren. Bewerkingen die je daarin doet worden ook geexporteert.
Wat alleen niet kan is kiezen naar welke namespace je wilt exporteren.

**Comment by rokkie** [comment]
Volgens mij werkt dit nu of niet?
Zie: #29

**Comment by ookgezellig** [comment]
Ja, werkt nu inderdaad, issue kan dus dicht
