### ISSUE TITLE
Reproductiemethode in infobox nog niet OK

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#13]
Ik doe een preview van Winkel nr 1, zie screenshot
![bug12](https://cloud.githubusercontent.com/assets/6546244/12451657/e0eebf26-bf8a-11e5-8eaf-b9e576bc6092.JPG)

Bij het veld Reproductiemehode staat nu Stenc., moet zijn "Gestencild"

**Comment by rokkie** [comment]
Moet de waarde voor de infobox dan ook uit de map komen?

**Comment by ookgezellig** [comment]
Yes!

**Comment by rokkie** [comment]
Ik heb m klaar staan, maar wacht nog even op die map voor verschijningsfrequenties, dan kan die in dezelfde commit mee.

**Comment by ookgezellig** [comment]
De map voor de verschijningsfrequentie gingen we niet doen, uit de mailwisseling van gisteren:  

"De verschijningsfrequentie mapping heb ik niet gedaan, te veel werk voor nu, die veldwaarden worden vanzelf strak als Gerard en ik de database updaten"

**Comment by ookgezellig** [comment]
Ik heb net de preview Winkel nr 1  weer getest, helaas staat er nog steeds 

| reproductiemethode      = Stenc.

**Comment by rokkie** [comment]
Zou nu gefixed moeten zijn

**Comment by ookgezellig** [comment]
Getest, gaat nu goed. Ik sluit m
