### ISSUE TITLE
[Preview Winkle nr 748 Sol Justitiase] Gerelateerde krant wordt 3x getoond

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#14]
Als ik de preview van Winkel 748 bekijk - http://127.0.0.1:8000/preview/748 - dan zie ik onder Gerelateerde kranten  drie maal 

* [[Ons volk; den vaderlant ghetrouwe]]

Moet 1x zijn, want in het Winkel-lemma wordt maar 1x "ONS VOLK, nr. 581" vernoemd 

Is dit iets in de db, of in de code?

**Comment by rokkie** [comment]
Ik zie m maar 1x, kun je nog eens een pull doen en de cache legen?

**Comment by ookgezellig** [comment]
Getest, gaat nu goed. Ik sluit de issue
