### ISSUE TITLE
Gerelateerde kranten -  incorrecte Wiki-syntax - in bodytekst en infobox

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#15]
Ik preview Winkel 199 - http://127.0.0.1:8000/preview/199

De drie gerelateerde krantentitels kloppen, maar de Wiki-opmaak in zowel de bodytekst (onder de kop == Gerelateerde kranten ==) als in de infobox is incorrect, want er wordt niet naar de volledige Wikipedia-titel van de krant verwezen

IS NU
* [[De Leidsche brief]]
* [[Sol justitiae; het Utrechts studentenblad]]
* [[Cereales vadenses]]

MOET ZIJN
* [[De Leidsche brief (verzetsblad, Leiden)]]
* [[Sol justitiae; het Utrechts studentenblad (verzetsblad, Utrecht)]]
* [[Cereales vadenses (verzetsblad, Wageningen)]]

(idem voor de infobox)

**Comment by rokkie** [comment]
Zou gefixed moeten zijn

**Comment by ookgezellig** [comment]
Getest, gaat goed

Ik heb nog 1 verzoek. Ivm de beschikbare ruimte in de infobox is het gebruikersvriendelijker om (alleen) daar niet de suffx "(verzetsblad, plaats)" te noemen, zeker voor titels die veel gerelateerde titels hebben 

![bug22](https://cloud.githubusercontent.com/assets/6546244/12512829/bd60d134-c11a-11e5-94f5-ba64cfde6781.JPG)

Dus in de Wiki-code (voor bv Winkel 199) wordt dat

| gerelateerd             = [[De Leidsche brief (verzetsblad, Leiden)|De Leidsche brief]] [[Cereales vadenses (verzetsblad, Wageningen)|Cereales vadenses]] [[Sol justitiae; het Utrechts studentenblad (verzetsblad, Utrecht)|Sol justitiae; het Utrechts studentenblad]]

**Comment by rokkie** [comment]
Done

**Comment by ookgezellig** [comment]
Getest en OK. Ik sluit de issue
