### ISSUE TITLE
Mapping inhoudsoorten.json nog niet geimplemeteerd?

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#16]
Ik preview Winkel 199 - http://127.0.0.1:8000/preview/199 - ik zie in de infobox en de bodytekst nog "Opinie" ipv "Opinie-artikelen" - zie screenshots

[inhoudsoorten_editOJ_20160220.txt](https://github.com/ookgezellig/verzetskranten/files/100790/inhoudsoorten_editOJ_20160220.txt)
![bug21](https://cloud.githubusercontent.com/assets/6546244/12511427/991ca81a-c111-11e5-8268-dfa124fdba8a.JPG)
![bug20](https://cloud.githubusercontent.com/assets/6546244/12511428/99334340-c111-11e5-9bb7-d8cbd7ef530b.JPG)

Mapping inhoudsoorten al geimplemeneerd? (bijgesloten)
 
Let op: graag in de infobox de eerste letter kapitaal (Opinie-artikelen) en in de bodytekst de eerste letter onderkast (opinie-artikelen)

**Comment by rokkie** [comment]
Zou gefixed moeten zijn

**Comment by ookgezellig** [comment]
Gestest, gaat nu goed. Ik sluit deze issue
