### ISSUE TITLE
Datumweergave te nauwkeurig weergegeven

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#17]
IK doe een preview van Winkel 961 - http://127.0.0.1:8000/preview/961

Ik zie bij de datums staan
| datum eerste uitgave    = 1 mei 1943 
| datum laatste uitgave   = 1 mei 1945 

In de data die ik aan Gerard heb aangeleverd (Excel-sheet) staat "mei 1943 en "mei 1945", dus zonder dagaanduiding. Zo moet het ook weergeven worden in de Wiki-code

Datumvelden kunnen bv. ook de (string)waarde hebben
- "najaar 1944"
- "1943"
- "ca. juni 1944"
- "begin 1944"
- "1943 (schatting)"
- "1944?"
- "ca. 20 september 1944"
- "medio 1944"
 
Dat moet dan ook precies zo in de Wiki-code komen

Hoe staat het in de db?

**Comment by rokkie** [comment]
in de DB staan 3 velden, te weten:
- `periodeVanVerschijnen`
- `tijdstipEersteUitgave`
- `tijdstipLaatsteUitgave`

In het veld `periodeVanVerschijnen` staan dingen als: "mei '43 - mei '45" 
In de andere velden staan gewoon datum notaties zoals: '1943-05'. Het probleem hiermee is dat als je een datumformatter gebruikt en die het laat formatteren als d-m-y, hij al deze waarden invult, ook als er ontbrekende zijn. Het is in deze dus een afweging tussen consistentie/uniformteit en accuratesse.

**Comment by ookgezellig** [comment]
Dus als ik het goed begrijp zou Gerard voor "tijdstipEersteUitgave" en "tijdstipLaatsteUitgave" de db moeten aanpassen en die velden naar type=string moet omzetten ? (waarna jij de datumformatter niet meer nodig zou hebben?)

Omdat er toch niet verder met de datums gerekend wordt, lijkt mij dat datum als string geen problemen oplevert...

**Comment by rokkie** [comment]
Dat zou een oplossing zijn

**Comment by ookgezellig** [comment]
OK, dat ga ik dan met Gerard opnemen

**Comment by ookgezellig** [comment]
Oplossing:

alles laten zoals het nu is, want het gaat voor de meerderheid van de titels wel gewoon goed. We vragen Wikipedianen/community de data handmatig te controleren als ze met een beginnetje aan de slag gaan. 

Deze issue is dus opgelost, dus ik sluit 'm
