### ISSUE TITLE
Plaats van uitgave error 

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#18]
Ik doe: http://127.0.0.1:8000/preview/750

Deze krant heeft geen plaats van uitgave - "(verzetsblad, z.p.)" in de titel 

Ik zie: 
Method "PlaatsUitgave" for object "stdClass" does not exist in default\wiki.html.twig at line 60

![bug24](https://cloud.githubusercontent.com/assets/6546244/12513591/d80a031c-c11e-11e5-9564-fbab1597960b.JPG)
![bug23](https://cloud.githubusercontent.com/assets/6546244/12513592/d8295a28-c11e-11e5-8835-336c13abc527.JPG)

**Comment by rokkie** [comment]
Aangepast, default nu naar blanco

**Comment by ookgezellig** [comment]
Getest & OK, gaat goed, maar nu datumfout, zie aparte issue daarover. 

Ik sluit deze issue
