### ISSUE TITLE
Datumfout 

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#19]
Ik doe: http://127.0.0.1:8000/preview/750

In de infobox en de lopende tekst zie ik de datum van vandaag 22 januari 2016. 

![bug25](https://cloud.githubusercontent.com/assets/6546244/12514290/eec96d46-c122-11e5-81e8-573bc5f27d73.JPG)
![bug26](https://cloud.githubusercontent.com/assets/6546244/12514314/0eadf32a-c123-11e5-809a-3bd0f0c0425e.JPG)

Da's incorrect. Als er geen waarde in de db staat, moet ie niet de datum van vandaag weergeven, maar blanco.

**Comment by ookgezellig** [comment]
Zie ook http://127.0.0.1:8000/preview/1115 , ook bij datum eerste utgave geeft ie 22 jan 2016

![bug28](https://cloud.githubusercontent.com/assets/6546244/12514692/dcefa872-c124-11e5-8e6c-7b30162310a7.JPG)

**Comment by rokkie** [comment]
Als #17 is opgelost gaat deze vanzelf ook goed.

**Comment by ookgezellig** [comment]
#17 is gesloten, dus deze kan ook dicht
