### ISSUE TITLE
Mensevriendelijke naam downloadbaar zipbestand

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#2]
Selecteer 1 of meerdere titels. Klik op Download-knop. Het bestand heet dan bv wikis-145256795.zip. Hieraan kan ik niet zien welke titels ik in de zip kan verwachten

Issue heeft geen priorteit op dit moment

**Comment by rokkie** [comment]
Ik had eerst de winkelsnr's in de bestandsnaam gebruikt, maar realiseerde mij daarna dat je dat bij grote batches hele lange bestandsnamen krijgt. Ik heb daarom besloten om gewoon een timestamp te gebruiken. Als jij een idee hierover hebt, hoor ik dat graag.

**Comment by ookgezellig** [comment]
Ja, dat besefte ik ook, dat bij grote batches de zipbestandsnaam uit de hand gaat lopen. IK heb niet 123 een idee hoe dat wel zou kunnen... Kun je de timestamp als wikis-dd-mm-yyyy-hh-mm-ss.zip formatteren, das net iets inzichtelijker

**Comment by rokkie** [comment]
sure, das geen punt

**Comment by ookgezellig** [comment]
Getest, werkt goed!
