### ISSUE TITLE
Als er geen plaats van uitgave is, dan geen "in" in de bodytekst weergeven

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#20]
Ik doe http://127.0.0.1:8000/preview/1061

Ik zie in de bodytekst " dat tot en met 1 mei 1945 in  werd uitgegeven."

![bug27](https://cloud.githubusercontent.com/assets/6546244/12514511/1c77b0b2-c124-11e5-88a4-2c0facf79fb5.JPG)

Omdat er geen plaats van uitgave is, moet het woordje "in" niet weergegeven worden

**Comment by rokkie** [comment]
Blijkbaar is er een geval waarin de query voor plaatsen van uitgave ook records teruggeeft als de plaatsnaam leeg is. Ik moet dit even aan Gerard voorleggen.

**Comment by ookgezellig** [comment]
OK

**Comment by rokkie** [comment]
Heb t zelf al gevonden. Zou nu moeten werken.

**Comment by ookgezellig** [comment]
Er staat nu
 "dat tot en met 1 mei 1945 . Het blad verscheen "

moet zijn
"dat tot en met 1 mei 1945 werd uitgegeven. Het blad verscheen"

**Comment by rokkie** [comment]
Done

**Comment by ookgezellig** [comment]
Gestest en OK. Issue gaat dicht
