### ISSUE TITLE
Foutmelding als krant geen titels heeft 

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#21]
Bv. http://127.0.0.1:8000/preview/1170

![bug29](https://cloud.githubusercontent.com/assets/6546244/12514983/4a588f22-c126-11e5-94a6-fe8bdde6ee78.JPG)

**Comment by rokkie** [comment]
Wat moet er met de lopende tekst gebeuren als er geen titel is?

**Comment by ookgezellig** [comment]
O ja... Dat moet gewoon worden: Zonder titel was een verzetsblad uit de Tweede Wereldoorlog... 

(we gaan die titelloze bladen nog apart verder  bewerken)

**Comment by rokkie** [comment]
ik heb nu `Ongetiteld verzetsblad`. Is dat ook goed?

**Comment by ookgezellig** [comment]
Ja, ik ook prima!

**Comment by rokkie** [comment]
Bij deze

**Comment by ookgezellig** [comment]
Gestest en OK. Ik sluit m
