### ISSUE TITLE
Download van blad zonder titel geeft foutmelding

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#22]
IK wil nr 1132 downloaden  - http://127.0.0.1:8000/wiki/download?ids=[%221132%22]

Ik krijjg deze foutmelding

![bug30](https://cloud.githubusercontent.com/assets/6546244/12516620/a1b1815e-c12e-11e5-9977-d5d37cd4ebe7.JPG)

**Comment by rokkie** [comment]
Gefixed, de titels van de wiki worden nu gebruikt.

**Comment by ookgezellig** [comment]
Getest en OK. Issue gaat dicht
