### ISSUE TITLE
error Method "oplageMax" for object "stdClass" does not exist in default\wiki.html.twig at line 87 

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#23]
Ik doe http://127.0.0.1:8000/preview/1019

Ik krijg error Method "oplageMax" for object "stdClass" does not exist in default\wiki.html.twig at line 87 

![bug31](https://cloud.githubusercontent.com/assets/6546244/12590390/140d76fe-c463-11e5-98e6-316474bece8c.JPG)

**Comment by rokkie** [comment]
gefixed

**Comment by ookgezellig** [comment]
Getest en OK bevonden. Op slot dus
