### ISSUE TITLE
Opmerking dat het artikel is gemaakt in het kader van het Wikiproject Verzetskranten, verplaatsen naar de overlegpagina van het artikel

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#25]
Zie bijvoorbeeld Overleg:Piłsudski-plein
https://nl.wikipedia.org/wiki/Overleg:Pi%C5%82sudski-plein

**Comment by rokkie** [comment]
Wanneer je een artikel exporteerd, checkt ie of een corresponderende overleg pagina al bestaat. Als dit niet het geval is, maakt ie deze aan met de disclaimer als content.

**Comment by rokkie** [comment]
De disclaimer is weer terug op de pagina van het artikel en op de overlegpagina staat nu
`Dit artikel is geschreven in het kader van het [[Wikipedia:Wikiproject/Verzetskranten|Wikiproject Verzetskranten]]`
Wel is het zo dat artikelen waar al een overleg pagina van bestaat wordt deze niet overschreven.
Dit werkt dus alleen voor artikelen waar geen overleg pagina van bestaat (omdat de content toch altijd hetzelfde is).

**Comment by ookgezellig** [comment]
OK, goede overweging om bestaande overlegpagina's te ontzien. 

Getest en OK, issue dus dicht
