### ISSUE TITLE
Referentie naar Winkel-nrs toevoegen aan Gerelateerde kranten

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#26]
In het lijstje onder het kopje Gerelateerde kranten: voor elke gerelateerde krant een verwijzing naar het corresponderende Winkel-lemma opnemen (indien dat lemma er is)

Voorbeeld (zie https://nl.wikipedia.org/wiki/Wikipedia:Wikiproject/Verzetskranten/Beginnetjes/De_Geus_onder_studenten_%28verzetsblad,_Den_Haag%29)

Opm Olaf voor Rocco: in de wiki.html.twig : Er staat nu (onder kopje "Gerelateerde kranten") 
"Lemma NN .....". Kun jij er voor zorgen dat daar dan het corresponderende Winkel-nr verscijnt ipv NN

**Comment by rokkie** [comment]
gefixed

**Comment by ookgezellig** [comment]
Nog niet OK:, het Winkel-ID van de gerelateerde krant(en) moet verwijzen naar die gerelateerde krant(en), en niet - zoals nu - naar de krant zelf

Zie bv. http://127.0.0.1:8000/preview/731A

== Gerelateerde kranten ==
* [[Cocktail (verzetsblad)]]  <ref>''Cocktail'': Lemma** 731A** in [[:commons:File:PDF_of_De_Ondergrondse_Pers_1940-1945_-_derde_druk_-_1989.pdf|De ondergrondse pers 1940-1945]] (PDF)</ref>

Moet zijn
== Gerelateerde kranten ==
* [[Cocktail (verzetsblad)]]  <ref>''Cocktail'': Lemma **113A** in [[:commons:File:PDF_of_De_Ondergrondse_Pers_1940-1945_-_derde_druk_-_1989.pdf|De ondergrondse pers 1940-1945]] (PDF)</ref>

**Comment by rokkie** [comment]
Oeps, aangepast..

**Comment by rokkie** [comment]
Kan deze na het fixen van #28 niet ook dicht?

**Comment by ookgezellig** [comment]
Deze kan inderdaad dicht, heb ik getest en werkt prima
