### ISSUE TITLE
Mapping verschijningsfrequentie

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#27]
Olaf mapt strings in verschijningsfrequenties.json, Rocco implementeert . 

Op dezelfde manier als Reproductiemethode (issue #13) en Inhoudsoorten (issue #16)

[verschijningsfrequenties.txt](https://github.com/ookgezellig/verzetskranten/files/124741/verschijningsfrequenties.txt)
Bijlage: hernoem .txt naar .json

**Comment by ookgezellig** [comment]
[verschijningsfrequenties_editOJ20160211.txt](https://github.com/ookgezellig/verzetskranten/files/125125/verschijningsfrequenties_editOJ20160211.txt)

txt nernoemen naar json

**Comment by rokkie** [comment]
gefixed

**Comment by ookgezellig** [comment]
Getest en OK bevonden. Dus  close ik m
