### ISSUE TITLE
Preview + download Winkelnr 406 gaat mis

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#28]
* Als ik ga naar http://127.0.0.1:8000/preview/406, dan krijg ik de foutmelding Method "EindWinkelNr" for object "stdClass" does not exist in default\wiki.html.twig at line 117 (zie bijlage)
![bug40](https://cloud.githubusercontent.com/assets/6546244/13078544/124c7762-d4c0-11e5-95fc-b5392df8eb42.JPG)

Dit zowel als ik niet als wel ben ingelogd

* Als ik 406 wil downloaden (http://127.0.0.1:8000/wiki/download?ids=[%22406%22]), klapt de server eruit, zie 2 screenshots
![bug42](https://cloud.githubusercontent.com/assets/6546244/13078591/5aaab654-d4c0-11e5-92b2-5767a319d1b7.JPG)
![bug41](https://cloud.githubusercontent.com/assets/6546244/13078592/5aabc0ee-d4c0-11e5-9d3f-bf2fb56c969d.JPG)

**Comment by ookgezellig** [comment]
Ook (ingelogd) exporteren werkt niet
![bug43](https://cloud.githubusercontent.com/assets/6546244/13078701/e3e7272c-d4c0-11e5-8186-a2c2c9c18be9.JPG)
iet:

**Comment by rokkie** [comment]
Bij mij werkt ie gewoon. Misschien beetje suffe vraag, maar heb je de cache al een keer geleegd?

**Comment by ookgezellig** [comment]
Cache legen... seems to do the trick indeed! Het werkt, dus issue gaat dicht
