### ISSUE TITLE
Exportfunctie met ingelogde gebruiker geeft IP-adres piv gebruikersnaam in WP-stub history

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#29]
Als ik op http://127.0.0.1:8000 inlog onder mijn eigen Wiki-account en ik exporteer een artikel ()bv .https://nl.wikipedia.org/wiki/Wikipedia:Wikiproject/Verzetskranten/Beginnetjes/Aan_het_Nederlandsche_volk_%28verzetsblad,_Eindhoven%29, dan zie ik in de history van die WP-pagina niet mijn WP-username, maar mijn IP-adres.

Dat WP denkt dat ik een niet-geregistreerde gebruiker ben is nadelig omdat 
1: "Als je vanaf een IP-adres werkt waar veel mensen gebruik van maken (een school, een bibliotheek of een bedrijf), kan het zijn dat iemand anders vandalistische wijzigingen maakt, waarna het IP-adres wordt geblokkeerd. Als je niet aangemeld bent, word je dan meegeblokkeerd, maar ingelogde gebruikers kunnen meestal blijven bewerken na een dergelijke blokkade"

2: Niet meer dan 1 export (per uur (?) lijk te kunnen doen, ik kan iig geen bv. 3 exports tegelijk doen. De 1e export lijk goed te gaan, maar 2e en 3e WP-pagina's die aangemaakt zouden moeten zijn, zie ik niet terug in de lijst https://nl.wikipedia.org/wiki/Speciaal:NieuwePaginas?namespace=all&tagfilter=&username=, waaruit ik afleid dat ze dus niet zijn aangemaakt 
Heeft wellicht te maken met de captach-melding waarover Rocco sprak

**Comment by rokkie** [comment]
Euvel gevonden, de sessie werd niet bewaard waardoor de login genegeerd werd.
Dit is gefixed, maar je moet lokaal nog een keer `composer install` draaien nadat je geupdated hebt.

**Comment by ookgezellig** [comment]
Werkt nu briljant, erg fraai! 
Zie bv eerste rijen op https://nl.wikipedia.org/wiki/Wikipedia:Wikiproject/Verzetskranten/Beginnetjes#A

Ik zie alleen dat de {{DisclaimerVerzetskrantenproject}} nu op de Overlegpagina vh artikel neergezet wordt, en niet (zoals het zou moeten) bovenaan de pagina

Wat wel automatisch op de overlegpagina neergezet mag worden is dit stukkje Wiki-code:
* Dit artikel is geschreven in het kader van het [[Wikipedia:Wikiproject/Verzetskranten|Wikiproject Verzetskranten]]

**Comment by ookgezellig** [comment]
Ik zie nog iets: Als  je in de Geschiedenis van https://nl.wikipedia.org/w/index.php?title=Wikipedia:Wikiproject/Verzetskranten/Beginnetjes/Alles_sal_reg_kom!_%28verzetsblad,_Haarlem%29&action=history kijkt, zie je dat er 4 edits gedaan zijn. De inhoudsvorm wordt daarbij overgeschreven: algemene artikelen,  humor,  binnenlandse berichten, nieuwsberichten

Daaruit leid ik af dat er in de database alle 4 de vormen opgeslagen zijn (ik dacht dat het er altijd maar 1 was). Klopt dat?

Zo ja: Is het mogelijk om zowel in de infobox (veld "inhoud") als in de bodytekst alle 4 de inhoudsvormen te vermelden?

**Comment by rokkie** [comment]
Ik weet niet hoeveel inhoudsvormen er in de database staan, ik moet dat even controleren. Kun je hier een aparte issue voor aanmaken?
Volgens mij is deze nu gefixed, evenals #25

**Comment by ookgezellig** [comment]
En ik zie nog wat: in https://nl.wikipedia.org/w/index.php?title=Wikipedia:Wikiproject/Verzetskranten/Beginnetjes/Alles_sal_reg_kom_%28verzetsblad,_Deviezeninstituut,_Amsterdam%29&action=history 

zie ik dat de reproductiemethode ook overschreven wordt: 
Was in de oorspronkelijke versie "Aanvankelijk getypt, na 12 oktober 1944 gestencild" (wat correct is), maar in de 2e versie is dit vervangen door "Gestencild"

https://nl.wikipedia.org/w/index.php?title=Wikipedia:Wikiproject/Verzetskranten/Beginnetjes/Alles_sal_reg_kom_%28verzetsblad,_Deviezeninstituut,_Amsterdam%29&diff=46041894&oldid=46041891

**Comment by ookgezellig** [comment]
Gestest en OK bevonden. Issue dus dicht
