### ISSUE TITLE
[Exportfunctie] Inhoudsvormen overschreven

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#30]
Als je in de Geschiedenis van https://nl.wikipedia.org/w/index.php?title=Wikipedia:Wikiproject/Verzetskranten/Beginnetjes/Alles_sal_reg_kom!_%28verzetsblad,_Haarlem%29&action=history kijkt, zie je dat er 4 edits gedaan zijn. De inhoudsvorm wordt daarbij overgeschreven: algemene artikelen, humor, binnenlandse berichten, nieuwsberichten

Daaruit leid ik af dat er in de database alle 4 de vormen opgeslagen zijn (ik dacht dat het er altijd maar 1 was). Klopt dat?

Zo ja: Is het mogelijk om zowel in de infobox (veld "inhoud") als in de bodytekst alle 4 de inhoudsvormen te vermelden?

**Comment by rokkie** [comment]
Er bleken inderdaad in sommige gevallen meerdere inhoudsvormen te bestaan. De query die de lijst met te exporteren bladen ophaalt retourneert dan meerdere 'records' voor een enkel blad. Hierdoor worden de betreffende bladen dus meerdere keren geexporteerd.
Ik heb de queries en het template aangepast om hier rekening mee te houden, het zou nu moeten werken.

**Comment by ookgezellig** [comment]
OK, gestest, werkt goed genoeg. Issue dus dicht
