### ISSUE TITLE
[Exportfunctie] Reproductievormen overschreven

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#31]
In https://nl.wikipedia.org/w/index.php?title=Wikipedia:Wikiproject/Verzetskranten/Beginnetjes/Alles_sal_reg_kom_%28verzetsblad,_Deviezeninstituut,_Amsterdam%29&action=history 

zie ik dat de reproductiemethode ook overschreven wordt: 
Was in de oorspronkelijke versie "Aanvankelijk getypt, na 12 oktober 1944 gestencild" (wat correct is), maar in de 2e versie is dit vervangen door "Gestencild"

https://nl.wikipedia.org/w/index.php?title=Wikipedia:Wikiproject/Verzetskranten/Beginnetjes/Alles_sal_reg_kom_%28verzetsblad,_Deviezeninstituut,_Amsterdam%29&diff=46041894&oldid=46041891

**Comment by rokkie** [comment]
Er bleken inderdaad in sommige gevallen meerdere reproductiemethoden te bestaan. De query die de lijst met te exporteren bladen ophaalt retourneert dan meerdere 'records' voor een enkel blad. Hierdoor worden de betreffende bladen dus meerdere keren geexporteerd.
Ik heb de queries en het template aangepast om hier rekening mee te houden, het zou nu moeten werken.
Een bijkomend nadeel is wel dat in bijv het specifieke geval van WinkelNr 17 staat:

> Aanvankelijk getypt, na 12 oktober 1944 gestencild en Gestencild

Ik kan hier niet echt wat aan doen. Het makkelijkst is dit gewoon in de database aan te passen.

**Comment by ookgezellig** [comment]
OK, getest, werkt goed genoeg. Issue dus dicht
