### ISSUE TITLE
Meervoudige plaats van uitgave wordt niet goed weergegeven in preview 

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#32]
Sommige kranten hadden meerdere plaatsen van uitgave, bv. 
* 28A --> Den Haag, Amsterdam
* 286 --> Arnhem, Nijmegen

(zie https://nl.wikipedia.org/wiki/Wikipedia:Wikiproject/Verzetskranten/Beginnetjes)

In de preview (bv. http://127.0.0.1:8000/preview/286) worden in de infobox (veld: "plaats van uitgave") niet alle plaatsen weergegeven. In de bodytekst gaat het wel goed. Idem voor bv http://127.0.0.1:8000/preview/506  

Bij http://127.0.0.1:8000/preview/411 gaat het als volgt mis:
PVU = Amsterdam-Rotterdam-'s-Gravenhage-Groningen, maar 
* in de infobox staat alleen _Rotterdam_
* in de bodytekst staat alleen "in _Den Haag_ werd uitgegeven"

Bij http://127.0.0.1:8000/preview/581 als volgt
PVU=Utrecht-Amsterdam-'s-Gravenhage
* in de infobox staat alleen _s-Gravenhage_
* in de bodytekst staat alleen "in _Den Haag_ werd uitgegeven"
(waarbij het niet gaat of er nu Den Haag of sGravenhage staat, maar wel dat er - itt tot bovenstaand geval - 2x dezelfde PVU staat)

**Comment by rokkie** [comment]
Zelfde verhaal als bij reproductiemethoden #31 en inhoudsvormen #30.
Zou nu gefixed moeten zijn.

**Comment by ookgezellig** [comment]
Getest, bij http://127.0.0.1:8000/preview/411 en http://127.0.0.1:8000/preview/581 gaat het nog niet goed, er wordt nog steeds maar 1 PVU weergegeven

**Comment by rokkie** [comment]
Plaats van Uitgave word in de DB gemarkeerd met zowel een `label` als een `name`. Volgens de query die gerard heeft aangeleverd heeft het 'label' de voorkeur. Zie:
https://github.com/ookgezellig/verzetskranten/blob/master/var/sparql/Plaats_van_uitgave.rq#L17
Daar is er bij WineklNr 411 maar 1 van. Je kunt dit fenomeen zien als je de query iets aanpast.
Zie her [resultaat](http://almere.pilod.nl/sparql?default-graph-uri=&query=PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+bf%3A+%3Chttp%3A%2F%2Fbibframe.org%2Fvocab%2F%3E%0D%0APREFIX+ns0%3A+%3Chttp%3A%2F%2Falmere.pilod.nl%2FLydiaWinkel%2F%3E%0D%0APREFIX+dct%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0D%0APREFIX+dbo%3A+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%0D%0A%0D%0ASELECT+DISTINCT+%28STR%28%3FwinkelID%29+AS+%3FWinkelNr%29%0D%0A++++++++++++++++%28STR%28%3Ftitel%29+AS+%3FBlad%29%0D%0A++++++++++++++++%28STR%28%3FppnF%29+AS+%3FPPNFysiek%29%0D%0A++++++++++++++++%28STR%28%3FppnD%29+AS+%3FPPNDigitaal%29%0D%0A++++++++++++++++%28STR%28%3Fplts1%29+AS+%3FPlaatsUitgave1%29%0D%0A++++++++++++++++%28STR%28%3Fplts2%29+AS+%3FPlaatsUitgave2%29%0D%0AFROM+%3Chttp%3A%2F%2Falmere.pilod.nl%2FLydiaWinkel%2F%3E%0D%0AWHERE+%7B%0D%0A++++%3Fts+a+ns0%3AUndergroundPublication+.%0D%0A++++OPTIONAL+%7B+%3Fts+bf%3AworkTitle%2Fbf%3AtitleValue+%3Ftitel+%7D+.++%23+Er+zijn+ook+bladen+zonder+titel%0D%0A++++%3Fts+ns0%3AidWinkel%2Fbf%3AidentifierValue+%3FwinkelID+.%0D%0A++++OPTIONAL+%7B+%3Fts+bf%3AhasInstance%2Fbf%3Apublication%2Fbf%3AproviderPlace%2Fbf%3Alabel+%3Fplts1+%7D++%23+Voorkeursvariant%0D%0A++++OPTIONAL+%7B+%3Fts+bf%3AhasInstance%2Fbf%3Apublication%2Fbf%3AproviderPlace%2Fdbo%3Aname+%3Fplts2+%7D%0D%0A++++OPTIONAL+%7B+%3Fts+bf%3AhasInstance%2Fns0%3AfysicalPPN-KB%2Fbf%3AidentifierValue+%3FppnF+%7D%0D%0A++++OPTIONAL+%7B+%3Fts+bf%3AhasInstance%2Fns0%3AdigitalPPN-KB%2Fbf%3AidentifierValue+%3FppnD+%7D%0D%0A++++FILTER%28STR%28%3FwinkelID%29+%3D+%22411%22%29%0D%0A%7D%0D%0AORDER+BY+%3FwinkelID+%0D%0A&should-sponge=&format=text%2Fhtml&timeout=0). 
Je kunt er voor kiezen om overal `PlaatsUitgave2` te gebruiken, maar dan mis je weer 'Den Haag'.

**Comment by rokkie** [comment]
Als je de voorkeur wilt geven aan `PlaatsUitGave2` kun je eenvoudigweg op regel 11:
https://github.com/ookgezellig/verzetskranten/blob/master/var/sparql/Plaats_van_uitgave.rq#L11
`plts1` en `plts2` omdraaien.

**Comment by ookgezellig** [comment]
Thanks, ik heb plts1 en plts 2 omgedraaid (in de devel branch), lijkt goed te werken inderdaad

**Comment by rokkie** [comment]
Top, dan merge ik de master branch OK?

**Comment by ookgezellig** [comment]
Net nog wat teste gedaan, en alles lijkt goed te werken. Ik denk dat we dan klaar zijn, issue gaat duc dicht en je kunt wmb de masterbranch mergen.
