### ISSUE TITLE
[Winkel nr 4 preview] Datumweergave klopt niet (3x)

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#5]
Ik heb de Wiki-code van Winkel nr 4 op Wikipedia gezet, met als resultaat

https://nl.wikipedia.org/wiki/Wikipedia:Wikiproject/Verzetskranten/Beginnetjes/De_Accu:_Nederlandse_berichten_van_de_B%28etrouwbare%29.B%28erichten%29.C%28entrale%29._%28verzetsblad,_Amsterdam%29

1) In de infobox rechts klopt de datum van het veld "Datum laatste uitgave" niet: 
IS NU:  19-01-2016
MOET ZIJN: 11 mei 1945

2) Dus ook: weergave van de maanden in tekst (mei) ipv getallen (05) is gewenst

3) Ook in de lopende tekst klopt het niet. 
IS NU "uit de Tweede Wereldoorlog, dat vanaf 11-10-1944 in Amsterdam werd uitgegeven".
MOET ZIJN:  uit de Tweede Wereldoorlog, dat vanaf 11 oktober 1944 tot en met 11 mei 1945 in Amsterdam werd uitgegeven".

Vraag: is dit iets in de database, of in de code?

**Comment by rokkie** [comment]
Dit zit in het template. Op de betreffende plaatsen zie je staan: `date('d-m-Y')`. Hiermee wordt de datum geformateerd. Ik heb nu de zgn 'locale' op NL gezet en een template extensie gebruikt om de datums in nederlands te renderen.

**Comment by ookgezellig** [comment]
Getest, lijkt nu goed te gaan. Ik sluit de issue
