### ISSUE TITLE
[Winkel nr 5] Diverse issues

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#7]
![bug5](https://cloud.githubusercontent.com/assets/6546244/12426520/54fa3f0a-beda-11e5-8580-366d3ba85ac4.JPG)
Test obv https://nl.wikipedia.org/wiki/Wikipedia:Wikiproject/Verzetskranten/Beginnetjes/Accu-vonken:_uitgave_van_De_Accu_-_Artikelen_van_algemeen_belang_%28verzetsblad,_Amsterdam%29

Zie rode tekst in bijgevoegde schreenshots
![bug4](https://cloud.githubusercontent.com/assets/6546244/12426389/bc6844bc-bed9-11e5-8f00-63d25f80803a.JPG)

- Oktober ipv 10
- Datum laatste uitgave niet correct
- Velden met dummy leeglaten
- Onder de kop "Gerelateerde kranten" zou ik Nr 4 "De Accu..."verwachten. Is dit een database issue?
- Kop Gerelateerde personen weglaten, die zijn er immers bij deze krant niet  
- Link naar catalogus onderaan infobox moet obv de andere PPN gemaakt worden

- 3 a 4 keer per week : diakriet correct weergeven. Opmerking Olaf: blijkt te komen dor de editor waarmee ik het .wiki bestand open, die verneukt de diacrieten. Openen met bv. Word voorkomt dit probleem. Deze deelissue kan dus dicht

**Comment by rokkie** [comment]
Wordt gedupliceerd in andere issues.
