### ISSUE TITLE
[Winkel nr 8] Tekstuele fouten

### ISSUE THREAD

**Issue by ookgezellig** [ookgezellig/verzetskranten#8]
Zie screenshot: 

- moet "gedrukt" zijn i.p.v. "druk". Is dat een db-issue of een code issue?
- einddatum (augustus 1944) ontbreekt (zie ook nrs 4 en 5)

![bug6](https://cloud.githubusercontent.com/assets/6546244/12427107/953e4626-bedd-11e5-837a-e5618a39241f.JPG)

**Comment by rokkie** [comment]
'repoductiemethode komt uit DB'.
Ik zal een lijstje maken met alle verschillende zodat er een map gemaakt kan worden.

**Comment by ookgezellig** [comment]
Getest, gaat nu goed voor beide punten. Ik sluit de issue
